blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discordapp.com/
    about: Contact through PatrickKR#8110
  - name: Email
    url: mailto:PatrickKR@teamif.io
    about: Contact me on this mail
